# name: Continous Integration

# on:
#   push:
#     branches: ["production"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [20.x]
#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js ${{matrix.node-version}}

#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{matrix.node-version}}
#           cache: 'npm' # Speeds up dependencies installation process

#       - run: npm ci # A command to ensure that we have consistent and reliable builds
#       - run: npm run build


name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                       # Build context (root of the repo)
          file: ./Dockerfile               # Path to the Dockerfile
          push: true                       # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/movie-box:latest


